name: Aesthetic code referee

on:
    [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js environment
      uses: actions/setup-node@v1.4.2
    
    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Feasibility measurement
      run: yarn build

    - name: Aesthetic measurement
      run: yarn lint
